name: AtomicDex-Desktop CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 1'

jobs:
  
  ci-flow:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        name: [
          ubuntu-qt-5-15-0,
          ubuntu-qt-5-15-1,
          osx-qt-5-15-0,
          osx-qt-5-15-1,
          windows-10-qt-5-15-0,
          windows-10-qt-5-15-1
        ]
    
        include:
          - name: ubuntu-qt-5-15-0
            os: ubuntu-16.04
            qt: '5.15.0'

          - name: ubuntu-qt-5-15-1
            os: ubuntu-16.04
            qt: '5.15.1'

          - name: osx-qt-5-15-0
            os: macos-latest
            qt: '5.15.0'

          - name: osx-qt-5-15-1
            os: macos-latest
            qt: '5.15.1'

          - name: windows-10-qt-5-15-0
            os: windows-latest
            qt: '5.15.0'

          - name: windows-10-qt-5-15-1
            os: windows-latest
            qt: '5.15.1'
    
    steps:
      - uses: actions/checkout@v2

      - name: Install QT (Linux)
        if: runner.os == 'Linux'
        uses: KomodoPlatform/install-qt-action@v2
        with:
          version: ${{ matrix.qt }}
          host: 'linux'
          target: 'desktop'
          dir: '${{ github.workspace }}'
          modules: 'qtcharts qtwidgets debug_info'
          aqtversion: '==0.8'
          py7zrversion: '==0.6'

      - name: Install QT (MacOS)
        if: runner.os == 'macOS'
        uses: KomodoPlatform/install-qt-action@v2
        with:
          version: ${{ matrix.qt }}
          host: 'mac'
          target: 'desktop'
          dir: '${{ github.workspace }}'
          modules: 'qtcharts qtwidgets debug_info'

      - name: Install QT (Windows)
        if: runner.os == 'Windows'
        uses: KomodoPlatform/install-qt-action@v2
        with:
          version: ${{ matrix.qt }}
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          dir: 'C:\'
          modules: 'qtcharts qtwidgets debug_info'
